
GET http://localhost:3001/states/ 

###
GET http://localhost:3001/states/8/

###
POST http://localhost:3001/districts/

###
GET http://localhost:3001/districts/322/

###
DELETE http://localhost:3001/districts/320/ 

###
PUT http://localhost:3001/districts/323/

###
GET http://localhost:3001/states/11/stats 

###
GET http://localhost:3001/districts/11/details/ 